# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
  echo "setting up python"
  displayName: 'Setup Python 3.6'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- script: |
    make install
  displayName: 'Install dependencies'  
- script: |
    make lint
  displayName: 'Linting with pylint'
- script: |
    make test
  displayName: 'Test with pytest'
